### ISSUE TITLE
x.tags available only after get or set a tag

### ISSUE THREAD

**Issue by romagnolid** [mdshw5/simplesam#16]
```
>>> x = next(in_bam)
>>> print(x.tags)
None
>>> x.tags["RG"]
'1'
>>> x.tags
{'XU': 'cgttttaa', 'XB': 'cttacgttaagagttaac', 'MD': '75', 'NM': 0, 'NH': 1, 'RG': '1'}
```
I reckon that keeping a variable **x._tags** separated from **x.tags** allows to retrive the original tags but shouldn't x.tags already be parsed with 

     self.tags = parse_sam_tags(self._tags)

when a new read is initialized?

**Comment by mdshw5** [comment]
Yeah, this is definitely confusing behavior. The reasoning was to defer the parsing of the tags string to key value pairs, since not every `Sam` object will have its tags accessed. What I'll do is implement `Sam.tags` as a property that calls `parse_sam_tags` if key/value lookup hasn't been initialized. Good catch!

**Comment by mdshw5** [comment]
Can you confirm that the current master branch works as you expect? You can install to test using pip:

    pip install -e git+https://github.com/mdshw5/simplesam.git#egg=simplesam

If this solves your issue, then I'll tag and release a new version to PyPI.

**Comment by romagnolid** [comment]
Yep, solved!
Thanks for the quick fix and the useful package.
:+1:

**Comment by mdshw5** [comment]
Great. This should be up on PyPI in a few minutes.
